### ISSUE TITLE
SETNEWNAME | <new_name> | <new_name> <old_name> (4 marks)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#10]
Manages the contents of the HALshell command alias list. The first option deletes all command aliases defined in the current session. The second option deletes a specific command alias defined in the current session. The third option defines a new command alias in the current session. The new_name should always consist of a command with no parameters. The old_name may have parameters. For example, if the user enters SETNEWNAME wnn on the command line, the alias wnn will be deleted from the command alias list. Similarly, if the user enters SETNEWNAME wnn writenewnames HALshellAliases, wnn will be defined as an alias for the command writenewnames HALshellAliases in the command alias list. If an alias with the same name already exists, then the new alias replaces the old alias.

**Comment by streibeb** [comment]
Overwriting doesn't work

**Comment by streibeb** [comment]
WORKS
