### ISSUE TITLE
Alias Substitution (4 marks)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#14]
Before a command is executed, the command alias list should be checked to determine whether the command is an alias. When an alias is detected in a command, the old_name should be substituted for the new_name in the command before the command is executed. For example, if the user enters wnn on the command line, then writenewnames HALshellAliases should be substituted for wnn in the command. Now, assume the command alias list contains the following aliases:

w wnn
wnn writenewnames HALshellAliases

If the user enters w on the command line, then wnn should be substituted for w in the command, and then writenewnames HALshellAliases should be substituted for wnn in the command. That is, alias substitution should be recursive. Finally, assume the command alias list contains the following aliases:

w wnn
wnn writenewnames

If the user enters w HALshellAliases on the command line, then wnn should be substituted for w in the command, and then writenewnames should be substituted for wnn in the command. The command executed will be writenewnames HALshellAliases. This provides some flexibility in how alias substitution can be used.

**Comment by streibeb** [comment]
DONE!
