### ISSUE TITLE
SETSHELLNAME <shell_name> (2 marks)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#2]
Sets the shell name in the HALshell command prompt to shell_name. For example, the default command prompt (including the command counter described above), is shown below:

HALshell[27]>

If the user enters setshellname myshell on the command line, HALshell should display the following command prompt:

myshell[28]>

Store the shell name as the first record in a file. Initially, the record should contain the default shell name HALshell.

**Comment by streibeb** [comment]
Done
