### ISSUE TITLE
SETTERMINATOR <terminator> (1 mark)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#3]
Sets the terminator in the HALshell command prompt to terminator. If the user enters setterminator |-> on the command line, HALshell should display the following command prompt:

myshell[29]|->

Store the terminator as the second record in the same file as the shell name. Initially, the record should contain the default terminator >. The terminator may consist of any sequence of multiple characters.

**Comment by streibeb** [comment]
Done
