### ISSUE TITLE
SETHISTORYSIZE <n> (3 marks)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#4]
Sets the size of the HALshell command history queue to n, where n is a positive integer. For example, if the user enters sethistorysize 15 on the command line, HALshell will allocate a queue capable of holding 15 commands. Store the size of the command history queue as the third record in the same file as the shell name and terminator. Initially, the record should contain the default size 10.

**Comment by streibeb** [comment]
Done
