### ISSUE TITLE
SETNEWNAMESIZE <n> (2 marks)

### ISSUE THREAD

**Issue by JediCat** [streibeb/cs330_HALos#8]
Sets the size of the HALshell command alias list to n, where n is a positive integer. A command alias is simply another name by which a command can be referenced. For example, if the user enters setnewnamesize 15 on the command line, HALshell will allocate a list capable of holding 15 aliases. Store the size of the command alias list as the fourth record in the same file as the shell name, terminator, and command history queue size. Initially, the record should contain the default size 10.

**Comment by streibeb** [comment]
This was done, right?
